# 📂 Dataset Description

Dataset Name:
NASA CMAPSS Turbofan Engine Degradation Dataset (FD001)

Source:
NASA Prognostics Center of Excellence

Description:
This dataset contains operational settings and sensor measurements collected from simulated aircraft engines. It is widely used for predictive maintenance and Remaining Useful Life (RUL) analysis.

Business Objective:
Analyze engine operational data to identify degradation patterns and support maintenance decision-making.

## Key Features

- Engine_ID: Unique identifier for each aircraft engine.
- Cycle: Number of operational cycles completed.
- Operational Settings: Three variables representing operating conditions.
- Sensor Measurements: Twenty-one sensor readings monitoring engine health.

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(
    "../data/raw/train_FD001.txt",
    sep=r"\s+",
    header=None
)
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
5,1,6,-0.0043,-0.0001,100.0,518.67,642.10,1584.47,1398.37,14.62,...,521.68,2388.03,8132.85,8.4108,0.03,391,2388,100.0,38.98,23.3669
6,1,7,0.0010,0.0001,100.0,518.67,642.48,1592.32,1397.77,14.62,...,522.32,2388.03,8132.32,8.3974,0.03,392,2388,100.0,39.10,23.3774
7,1,8,-0.0034,0.0003,100.0,518.67,642.56,1582.96,1400.97,14.62,...,522.47,2388.03,8131.07,8.4076,0.03,391,2388,100.0,38.97,23.3106
8,1,9,0.0008,0.0001,100.0,518.67,642.12,1590.98,1394.80,14.62,...,521.79,2388.05,8125.69,8.3728,0.03,392,2388,100.0,39.05,23.4066
9,1,10,-0.0033,0.0001,100.0,518.67,641.71,1591.24,1400.46,14.62,...,521.79,2388.06,8129.38,8.4286,0.03,393,2388,100.0,38.95,23.4694

In [2]:
df.shape

(20631, 26)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20631 entries, 0 to 20630
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20631 non-null  int64
 1   1       20631 non-null  int64
 2   2       20631 non-null  float64
 3   3       20631 non-null  float64
 4   4       20631 non-null  float64
 5   5       20631 non-null  float64
 6   6       20631 non-null  float64
 7   7       20631 non-null  float64
 8   8       20631 non-null  float64
 9   9       20631 non-null  float64
 10  10      20631 non-null  float64
 11  11      20631 non-null  float64
 12  12      20631 non-null  float64
 13  13      20631 non-null  float64
 14  14      20631 non-null  float64
 15  15      20631 non-null  float64
 16  16      20631 non-null  float64
 17  17      20631 non-null  float64
 18  18      20631 non-null  float64
 19  19      20631 non-null  float64
 20  20      20631 non-null  float64
 21  21      20631 non-null  int64
 22  22      20631 non-null  int64
 23  23      20631 non-null  float64
 24  24      20631 non-null  float64
 25  25      20631 non-null  float64
dtypes: float64(22), int64(4)
memory usage: 4.1 MB

In [4]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,20631.00,20631.000000,20631.000000,20631.000000,2.063100e+04,...,20631.000000,20631.000000,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.0,20631.0,20631.000000,20631.000000
mean,51.506568,108.807862,-0.000009,0.000002,100.0,518.67,642.680934,1590.523119,1408.933782,1.462000e+01,...,521.413470,2388.096152,8143.752722,8.442146,3.000000e-02,393.210654,2388.0,100.0,38.816271,23.289705
std,29.227633,68.880990,0.002187,0.000293,0.0,0.00,0.500053,6.131150,9.000605,5.329200e-15,...,0.737553,0.071919,19.076176,0.037505,3.469531e-18,1.548763,0.0,0.0,0.180746,0.108251
min,1.000000,1.000000,-0.008700,-0.000600,100.0,518.67,641.210000,1571.040000,1382.250000,1.462000e+01,...,518.690000,2387.880000,8099.940000,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200
25%,26.000000,52.000000,-0.001500,-0.000200,100.0,518.67,642.325000,1586.260000,1402.360000,1.462000e+01,...,520.960000,2388.040000,8133.245000,8.414900,3.000000e-02,392.000000,2388.0,100.0,38.700000,23.221800
50%,52.000000,104.000000,0.000000,0.000000,100.0,518.67,642.640000,1590.100000,1408.040000,1.462000e+01,...,521.480000,2388.090000,8140.540000,8.438900,3.000000e-02,393.000000,2388.0,100.0,38.830000,23.297900
75%,77.000000,156.000000,0.001500,0.000300,100.0,518.67,643.000000,1594.380000,1414.555000,1.462000e+01,...,521.950000,2388.140000,8148.310000,8.465600,3.000000e-02,394.000000,2388.0,100.0,38.950000,23.366800
max,100.000000,362.000000,0.008700,0.000600,100.0,518.67,644.530000,1616.910000,1441.490000,1.462000e+01,...,523.380000,2388.560000,8293.720000,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.618400

In [5]:
column_names = [
    "Engine_ID",
    "Cycle",
    "Operational_Setting_1",
    "Operational_Setting_2",
    "Operational_Setting_3",
]
for i in range(1,22):
    column_names.append(f"Sensor_{i}")
df.columns = column_names

In [6]:
df.head()

,Engine_ID,Cycle,Operational_Setting_1,Operational_Setting_2,Operational_Setting_3,Sensor_1,Sensor_2,Sensor_3,Sensor_4,Sensor_5,...,Sensor_12,Sensor_13,Sensor_14,Sensor_15,Sensor_16,Sensor_17,Sensor_18,Sensor_19,Sensor_20,Sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [7]:
df["Engine_ID"].nunique()

100

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isnull().sum()

Engine_ID                0
Cycle                    0
Operational_Setting_1    0
Operational_Setting_2    0
Operational_Setting_3    0
Sensor_1                 0
Sensor_2                 0
Sensor_3                 0
Sensor_4                 0
Sensor_5                 0
Sensor_6                 0
Sensor_7                 0
Sensor_8                 0
Sensor_9                 0
Sensor_10                0
Sensor_11                0
Sensor_12                0
Sensor_13                0
Sensor_14                0
Sensor_15                0
Sensor_16                0
Sensor_17                0
Sensor_18                0
Sensor_19                0
Sensor_20                0
Sensor_21                0
dtype: int64

# Observation Table

| Observation          | Description                    |
| -------------------- | ------------------------------ |
| Rows                 | **20,631**                     |
| Columns              | **26**                         |
| Data Types           | **2 Integer, 24 Float**        |
| Missing Values       | **No missing values detected** |
| Unique Engines       | *(We'll calculate this next)*  |
| Total Sensors        | **21**                         |
| Operational Settings | **3**                          |

# Initial Observations

- The dataset contains operational records from multiple aircraft engines.
- Each row represents one engine at one operational cycle.
- There are three operational setting variables.
- Twenty-one sensor measurements are recorded for each cycle.
- No missing values were identified during the initial inspection.
- Column names were manually assigned because the raw dataset does not include headers.